import Features from '@/components/Features'
import Hero from '@/components/Hero'
import Navbar from '@/components/Header/NavBar'
import Head from 'next/head'
import Image from 'next/image'
import Steps from '@/components/Steps'
import Benefit from '@/components/Benefit'
import Faq from '@/components/Faq'
import Enquires from '@/components/Enquires'


export default function Home() {
  return (
    <>
      <Head>
        <title>Kimiko</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Features />
      <Steps />
      <Benefit />
      <Faq />
      <Enquires />
    </>
  )
}
